<?php

$adminLoggedIn = 0;
try{
    //check if adminhtml cookie is set
    if(array_key_exists('adminhtml', $_COOKIE)){
        //get session path and add dir seperator and content field of cookie as data name with magento "sess_" prefix
        $sessionFilePath = Mage::getBaseDir('session').DS.'sess_'.$_COOKIE['adminhtml'];
        //write content of file in var
        $sessionFile = false;
        if (is_file($sessionFilePath)) {
       		 $sessionFile = file_get_contents($sessionFilePath);
        }
    
        //save old session
        $oldSession = $_SESSION;
        //decode adminhtml session
        session_decode($sessionFile);
        //save session data from $_SESSION
        $adminSessionData = $_SESSION;
        //set old session back to current session
        $_SESSION = $oldSession;
    
        if(isset($adminSessionData['admin']) && is_array($adminSessionData['admin']) && array_key_exists('user', $adminSessionData['admin'])){
            //save Mage_Admin_Model_User object in var
            $adminLoggedIn = 1;
        }
    }
} catch (Exception $e){}
    
$storeId=Mage::app()->getStore()->getStoreId();

$helper=Mage::helper('autocompleteplus_autosuggest');

$uuid=$helper->getKey();

$onCatalog = false;

$product=Mage::registry('current_product');

$sku='';
$productUrl='';
$identifier='';

if($product) {
    $sku = $product->getSku();
    $productUrl = $product->getProductUrl();
    $identifier = $product->getId();
}

$magento_version = Mage::getVersion();
$extension_version = (string)Mage::getConfig()->getNode()->modules->Autocompleteplus_Autosuggest->version;
?>

<script async type="text/javascript" src="https://acp-magento.appspot.com/js/acp-magento.js?mage_v=<?php echo $magento_version ?>&ext_v=<?php echo $extension_version ?>&store=<?php echo $storeId?>&UUID=<?php echo $uuid?>&product_url=<?php echo urlencode($productUrl)?>&product_sku=<?php echo $sku?>&product_id=<?php echo $identifier?>&is_admin_user=<?php echo $adminLoggedIn?>"></script>
